### PR TITLE
Update packaging_guide.md

### PR DESCRIPTION
**Pull request by maelle**
Asking for a more minimal README than before and linking to a template. @ropensci/editors 

Thanks to a question by @robinsones

### CODE REVIEW

**Comment by sckott** [comment]
looks good to me, can i merge, or does anyone have objections

**Comment by noamross** [comment]
LGTM

**Comment by karthik** [comment]
LGTM

**Comment by karthik** [comment]
Before this PR is merged, can you also add the badge notes here? After _After a package is accepted..._

**Comment by karthik** [comment]
Sounds good. Frankly I think it can be at any stage after the issue is created. If the package moves forward, badges will update. Otherwise it will remain at unknown.

**Comment by maelle** [comment]
* I replaced http with https in the badge link in the editor guide @karthik 

* I've added the badge to the packaging guide in the README section.

**Pull request merged**
