### PR TITLE
Update README.Rmd

### PR DESCRIPTION
**Pull request by maelle**
Is this too minimal now @ropensci/editors?

### CODE REVIEW

**Comment by noamross** [comment]
I actually thought that the templates should be in the appendix of the book (in code blocks), but the _why_ and _how_ sections should stay.

**Comment by maelle** [comment]
Ah interesting! So the onboarding section of the gitbook would get a very minimal intro instead of https://ropensci.github.io/dev_guide/onboarding-why-what.html ? (i.e. what's in my branch README?)

**Comment by noamross** [comment]
Hm, I did kind of think that that stuff should be in both.  I want people to get the gist of things from coming to the onboarding repo landing page, but still have the dev guide be comprehensive.

**Comment by maelle** [comment]
Better?

**Pull request merged**
