### PR TITLE
Responding to requests for package fixes

### PR DESCRIPTION
**Pull request by sckott**
@noamross @maelle @karthik 

added a bit about maintainer responsiveness - opening up a discussion here 

thoughts on wording?  

there's been a few cases so far in which maintainers are slow to respond and then the CRAN pkg in question gets archived due to lack of maintainer responding/making the fix - I think we should have clear policies about this so that we can minimize pkgs falling into disrepair

### CODE REVIEW

**Comment by noamross** [comment]
This is fine, but I think the bigger question is: what happens when the CRAN package falls behind? We could say that we may request to have maintainer status transferred on CRAN, or ask up front that the author agrees that we (may) request to be assigned as maintainer if it is orphaned.  The latter would be helpful if a package is orphaned/removed from CRAN, and we want it back and need to appeal to the CRAN gods for it.

**Comment by sckott** [comment]
> ask up front that the author agrees that we (may) request to be assigned as maintainer if it is orphaned

yeah, seems reasonable to state this

**Comment by karthik** [comment]
The problem though is that CRAN will want the email to come from the maintainer. So if they are already not responding to emails about fixes, will they actually write to CRAN handing over maintainership to us?

**Comment by noamross** [comment]
That would only happen if they're unresponsive to us and CRAN.  The package
would be orphaned on CRAN if the maintainer doesn't respond to e-mails from
CRAN (as in the case of the package breaking with an R version update).  I
have no idea if, in that case, they would take transfer to us on GitHub and
agreement to our policies as sufficient reason for transfer to us without
the old maintainer's permission.

**Comment by maelle** [comment]
Sounds good, but does it make it sound as if joining Slack were compulsory?

**Comment by sckott** [comment]
i didn't intend for that, can change the wording - just a suggestion to help people stay in the loop

**Comment by sckott** [comment]
So: should we add wording that maintainers agree to let us ask for transfer of maintainership given x, y, z conditions are met?

**Comment by noamross** [comment]
Closed with #91

**Pull request closed without merging**
