### PR TITLE
Review process updates

### PR DESCRIPTION
**Pull request by noamross**
This is a blank PR for several updates.  

- [ ] Close outstanding [meta] tags
- [ ] Discuss and formalize various changes to packaging guidelines and onboarding that have been informally adopted over the past year.
- [ ] Re-organize the packaging guidelines, if necessary, to accommodate the increasing detail of recommendations. (Summary at top, then reference.)
- [ ] Provide guidance on writing blog posts/tech notes
- [ ] Write a blog post summarizing these changes, which may be part of a larger "Year in Reviews" post.

I'll try to keep commits well-organized and granular so that each represents a specific process or policy change.   Do drop both specific and general comments here as I go.

### CODE REVIEW

**Comment by noamross** [comment]
Should we add testing coverage via Coveralls/CI to requirements, meaning that we don't seek reviewers until it's there?  Right now it's recommended.  This would make it easier for editors to evaluate if there are major gaps in testing that should be addressed before review, and for reviewers, as well. We still need to test locally with `Sys.setenv(NOT_CRAN="true")` to assure that the right coverage is reported.

This makes for more onerous requirements, but its a relatively small leap once CI is set up.

**Comment by sckott** [comment]
> Should we add testing coverage via Coveralls/CI to requirements, meaning that we don't seek reviewers until it's there?

i think so. we may need to help some people - but is easy to do

**Comment by karthik** [comment]
+1 to adding coveralls. We are working on some setup tools to make that easier in the future.

**Comment by masalmon** [comment]
I don't remember where the discussion of having reviews as a single block vs. a shorter review with issues opened by reviewers in the package repo with mention of the review issue was? The former being what's currently done in the reviews I've read/written, the latter being how I saw you @noamross do a JOSS review. I really like the latter and starting doing it for JOSS reviews. Should this be a recommendation?

cc @njtierney 

I also see there was this thread https://discuss.ropensci.org/t/how-could-the-onboarding-package-review-process-be-even-better/302

**Comment by noamross** [comment]
@masalmon I personally prefer our longer-form reviews which keep most discussion in a single issue thread.  JOSS's style is specifically to avoid this.  I think that our style keeps the review history/discussion a relatively linear "document", allowing it to be read, learned from, and possibly re-used (as JOSS does).  JOSS's style makes for minimal extra overhead for package developers; as the review is just more issues in the repo, they mostly just continue their existing workflow.

I think linking to issues is fine in the main review, but prefer to keep major discussions in the main thread.  That's just my opinion, though, and I'd be happy to hear from others.

We revisit that conversation of "pulling against an empty/template repo" every once in a while.  So far I haven't been convinced that the awkwardness of that workflow is worth it.

**Comment by sckott** [comment]
thanks for your comments @masalmon 

I like the way we do it now, keeping most discussion in the onboarding issue thread. For pkgs I submit, I open issues in my pkg repo and link to those in the review issue, and do any discussion in the onboarding issue. 

I also think PR against empty repo is not warranted. Maybe we can revisit if our submissions increase dramatically, but right now we're at a pretty slow rate of submissions

**Comment by noamross** [comment]
Idea: Should we add a question asking the submitter to address how the package fits into RO? e.g., (which group it fits under in [our policies](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit))? I'm not sure submitters are looking at this, despite it being in the onboarding README.

**Comment by masalmon** [comment]
This sounds like it would make your editors' work much easier when phrasing a rejection @noamross :ok_hand: In this question you might add something like "if you're not too sure and don't want to fill the review for nothing you can make a more informal pre-review enquiry"

**Comment by noamross** [comment]
OK, with above "Perfect is enemy of the good commit", going to merge with if I get 2 thumbs up.  Also includes changes from #108 about package maintenance, including rOpenSci petitioning CRAN for transfer if package is abandoned.  Major outstanding issues include re-organizing policies for easier reading and clearer requirements v. maintenance, and updating the CoC (though I've added the checkmark for using the current CoC in issue template).   Removed the blog post, now currently on the "post" branch.

**Pull request merged**
